/**
 * @brief IIR Filter Includer
 * @file iirfilter.h
 * @author shenxfs 380406785@@qq.com
 * @date 2017-07-30
 * @version V1.0.0
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 29-Jul-2017 14:06:31
 * Discrete-Time IIR Filter (real and fixed point)
 * -------------------------------
 */
#ifndef IIR_FILTER_H
#define IIR_FILTER_H

#define NODE 4 /**<Second-Order Sections section=4*/

/**
*@struct  Discrete-Time IIR Filter Structure(REAL)
*/
typedef struct _fdata
{
  const double a[NODE][2];/**<Second-Order Sections a Coefficients a[NODE][0]-->a1,a[NODE][1]-->a2*/
  const double b[NODE][3];/**<Second-Order Sections b Coefficients b[NODE][0]-->b0,b[NODE][1]-->b1,b[NODE][2]-->b2*/
  const double g;         /**<Total gain Coefficients*/
  double wn[NODE][2];     /**<Delay Variabler*/
}fdata_t;

/**
*@struct  Discrete-Time IIR Filter Structure(Fixed Point)
*/
typedef struct _fdfix
{
  const int32_t a[NODE][2];/**<Second-Order Sections a Coefficients a[NODE][0]-->-a1,a[NODE][1]-->-a2,Q=30*/
  const int32_t b[NODE][3];/**<Second-Order Sections b Coefficients b[NODE][0]-->b0,b[NODE][1]-->b1,b[NODE][2]-->b2,Q=30*/
  const int32_t g;         /**<Total gain Coefficients,Q=30*/
  int32_t wn[NODE][2];     /**<Delay Variabler,Q=24*/
}fdfix_t;
extern fdata_t fd;
extern fdfix_t fx;
double iir_filter(double x,fdata_t *pfd);
void iir_filter_init(fdata_t *pfd);
int32_t fixiir_filter(int32_t x,fdfix_t *pfd);
void fixiir_filter_init(fdfix_t *pfd);
#endif
